name: Build Test

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Lint
        run: ./gradlew lintDebug --stacktrace

      - name: Build project
        run: ./gradlew assembleDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: |
            Auto PR for dev -> master
            Commits:
            ${{ join(github.event.commits.*.id, '\n') }}
          branch: auto-pr/dev-${{ github.run_number }}
          base: master
          title: "Auto PR: Dev branch update"
          body: |
            This pull request was automatically created after a successful CI build on `dev`.
            
            ## Included Commits
            ${{ join(github.event.commits.*.id, '\n') }}
            
            ## Commit Messages
            ${{ join(github.event.commits.*.message, '\n') }}
            
            Triggered by workflow: `${{ github.workflow }}`
            Run: `${{ github.run_id }}`
            Author: `${{ github.event.head_commit.author.name }}`
          draft: false
          delete-branch: true
          push-to-fork: false